Add corpse (task-106-G)
dargven/Cyborgs pull request #184
Opened 2023-12-24 14:58 UTC by EgorLukyanovich

2023-12-25 18:14 UTC, lapaigne requested changes
исправь по комментам

2023-12-25 18:14 UTC, lapaigne commented on client/src/components/Game/Player/Player.tsx
> +        if (hp !== 0){
а че просто if (hp) не написал?

2023-12-25 18:14 UTC, lapaigne commented on client/src/components/Game/Player/Player.tsx
> +    const onEnd = ({ currentFrameName, currentFrame }:any) => {
вместо `any` либо тип/интерфейс нормальный пропиши, либо аргументы по отдельности

2023-12-25 18:14 UTC, lapaigne commented on client/src/components/Game/Player/Player.tsx
> +        if(hp === 0){
пускай остается как есть, хотя я бы `if (!hp)` написал

2023-12-26 12:02 UTC, EgorLukyanovich commented on client/src/components/Game/Player/Player.tsx
> +            if (getDirection) {
Не совсем понял что ты от меня требуешь

2023-12-26 12:05 UTC, lapaigne commented on client/src/components/Game/Player/Player.tsx
> +            if (getDirection) {
`if (getDirection)` убери

2023-12-26 12:05 UTC, lapaigne commented on client/src/components/Game/Player/Player.tsx
> +            if (getDirection) {
и `?` в пропсах

2023-12-26 12:12 UTC, lapaigne commented
вроде нормально

2023-12-26 12:12 UTC, lapaigne approved these changes

2023-12-26 14:42 UTC, dargven approved these changes

2023-12-26 14:43 UTC, merged